addnewplaceseed
rikufonseca/globpaacker pull request #38
Opened 2022-01-10 14:30 UTC by Ilhembsk

I added places in the seeds.

2022-01-10 14:35 UTC, skhohar requested changes

2022-01-10 14:35 UTC, skhohar commented on db/seeds.rb
> +p1= Place.new(name: Musée Cantini,
I believe names must be strings

2022-01-10 14:35 UTC, skhohar commented on db/seeds.rb
still needs : 
- associate the right picture to each place
- doing a for each on an array of places in order to save them

2022-01-11 09:19 UTC, Ilhembsk commented on db/seeds.rb
> +p1= Place.new(name: Musée Cantini,
Done

2022-01-11 09:19 UTC, Ilhembsk commented on db/seeds.rb
done

2022-01-11 09:21 UTC, merged